apiVersion: v1
kind: Service
metadata:
  name: {{ include "checkmk.fullname" . }}
  annotations:
    field.cattle.io/targetWorkloadIds: '["deployment:{{ include "checkmk.name" . }}:{{ include "checkmk.fullname" . }}"]'
  labels:
{{ include "checkmk.labels.standard" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  ports:
    - port: 42
      targetPort: 42
      protocol: TCP
      name: default
  selector:
    workloadID_eventsystem: "true"
