apiVersion: v1
kind: Service
metadata:
  name: {{ include "checkmk.fullname" . }}
  annotations:
    field.cattle.io/targetWorkloadIds: '["deployment:{{ include "checkmk.name" . }}:{{ .Release.Name }}"]'
  labels:
    app.kubernetes.io/name: {{ include "mid-server.name" . }}
    helm.sh/chart: {{ include "mid-server.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    workloadID_eventsystem: "true"
