apiVersion: v1
kind: Service
metadata:
  name: {{ include "checkmk.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "checkmk.name" . }}
    helm.sh/chart: {{ include "checkmk.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    workload.user.cattle.io/workloadselector: {{ template "fullname" . }}
