apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cievent.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "cievent.name" . }}
    helm.sh/chart: {{ include "cievent.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cievent.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "cievent.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          imagePullSecrets: {{ .Values.image.pullSecrets }}
          env:
            - name: USERNAME
              value: {{ .Values.collection.logusername }}
            - name: PASSWORD
              value: {{ .Values.collection.logpassword }}
            - name: TZ
              value: {{ .Values.collection.tz }}
            - name: CONFIGURL
              value: {{ .Values.collection.configurl }}
            - name: CONFIGUSER
              value: {{ .Values.collection.configusername }}
            - name: CONFIGPASS
              valueFrom:
                secretKeyRef:
                  key:  configpassword
                  name: {{ .Release.Name }}-auth
            - name: MIDUSER
              value: {{ .Values.collection.miduser }}
            - name: MIDURL
              value: {{ .Values.collection.midurl }}
            - name: MIDPASSWORD
              valueFrom:
                secretKeyRef:
                  key:  midpassword
                  name: {{ .Release.Name }}-auth
            - name: LOCAL_LOG
              value: {{ .Values.collection.locallog }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
