apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  logpassword: {{ .Values.collection.logpassword | b64enc | quote }}
  midpassword: {{ .Values.collection.midpassword | b64enc | quote }}
  configpassword: {{ .Values.collection.configpassword | b64enc | quote }}
